config/routes.rb
JvRailsAudition::Application.routes.draw do
  resources :game_performances


  root to: 'teams#index'

  resources :teams

  resources :players do
    collection do
      get 'page/:page', action: :index
    end
    get 'report', action: :report
  end

  namespace :sponsor do
    resources :companies
  end

  resources :statistics, only: :index

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :age,
    :birth_city,
    :birth_country,
    :birth_day,
    :first_name,
    :foot,
    :height_cm,
    :image,
    :last_name,
    :nationality,
    :nickname,
    :position,
    :team_id,
    :team_uuid,
    :uuid,
    :weight_kg,
    :players_attributes

  validates_uniqueness_of :uuid

  belongs_to :team
  has_many :game_performances

  delegate :name, to: :team, prefix: true, allow_nil: true

  def report
    File.write("#{Rails.root}/tmp/report.txt", '')
  end

  def performances
    return GamePerformance.where(:player_id => self.id)
  end

  def total_games
    GamePerformance.all.count
  end

  def average_goals
    average_goals = 0.0
    performances.each do |game|
      average_goals += game.goals
    end
    average_goals = average_goals / total_games
  end

  def average_assists
    average_assists = 0.0
    performances.each do |game|
      average_assists += game.assists
    end
    average_assists = average_assists / total_games
  end

  def average_yellow_cards
    average_yellowcards = 0.0
    performances.each do |game|
      average_yellowcards += game.yellow_cards
    end
    average_yellowcards = average_yellowcards / total_games
  end

  def average_red_cards
    average_redcards = 0.0
    performances.each do |game|
      average_redcards += game.red_cards
    end
    average_redcards = average_redcards / total_games
  end

  def average_shots_per_game
    shots_per_game = 0.0
    performances.each do |game|
      shots_per_game += game.shots_per_game
    end
    average_shots_per_game = shots_per_game / performances.count
  end

  def average_pass_success_percentage
    total_success = 0.0
    performances.each do |game|
      total_success += game.pass_success_percentage
    end
    average_pass_success_percentage = (total_success / performances.count).round(2)
  end

  def average_aerial_duels_won
    aerial = 0.0
    performances.each do |game|
      aerial += game.aerial_duels_won
    end
    average_ariel_duels_won = aerial / performances.count
  end


end
# == Schema Information
#
# Table name: players
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  nickname      :string(255)
#  nationality   :string(255)
#  age           :integer
#  birth_day     :datetime
#  birth_country :string(255)
#  birth_city    :string(255)
#  position      :string(255)
#  foot          :string(255)
#  image         :string(255)
#  height_cm     :integer
#  weight_kg     :integer
#  uuid          :string(255)
#  team_uuid     :string(255)
#  team_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_players_on_team_id    (team_id)
#  index_players_on_team_uuid  (team_uuid)
#  index_players_on_uuid       (uuid) UNIQUE
#

# == Schema Information
#
# Table name: players
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  nickname      :string(255)
#  nationality   :string(255)
#  age           :integer
#  birth_day     :datetime
#  birth_country :string(255)
#  birth_city    :string(255)
#  position      :string(255)
#  foot          :string(255)
#  image         :string(255)
#  height_cm     :integer
#  weight_kg     :integer
#  uuid          :string(255)
#  team_uuid     :string(255)
#  team_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_players_on_team_id    (team_id)
#  index_players_on_team_uuid  (team_uuid)
#  index_players_on_uuid       (uuid) UNIQUE
#

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.includes(:team).page(params[:page])
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  def report
    @player = Player.find(params[:player_id])
    @player.report

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= simple_form_for(@player, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :nickname %>
    <%= f.input :nationality %>
    <%= f.input :age %>
    <%= f.input :birth_day %>
    <%= f.input :birth_country %>
    <%= f.input :birth_city %>
    <%= f.input :position %>
    <%= f.input :foot %>
    <%= f.input :image %>
    <%= f.input :height_cm %>
    <%= f.input :weight_kg %>
    <%= f.input :uuid %>
    <%= f.input :team_uuid %>
    <%= f.input :team_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/players/_paginator.html.erb
<%= page_entries_info pager %>

<div class="pull-right">
  <%= paginate pager,
    theme: 'twitter-bootstrap',
    pagination_class: 'pagination' %>
</div>

app/views/players/_player.html.erb
<tr>
  <td><%= player.id %></td>
  <td><%= image_tag(player.image) %></td>
  <td><%= player.first_name %></td>
  <td><%= player.last_name %></td>
  <td><%= player.nickname %></td>
  <td><%= player.nationality %></td>
  <td><%= player.age %></td>
  <td><%= player.position %></td>
  <td><%= player.team_name %></td>
  <td><%= link_to 'Show', player %></td>
  <td><%= link_to 'Edit', edit_player_path(player) %></td>
  <td><%= link_to 'Destroy', player, data: { confirm: 'Are you sure?' }, method: :delete %></td>
</tr>

app/views/players/edit.html.erb
<div class="page-header">
  <%= link_to players_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to @player, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1>Editing player</h1>
</div>

<%= render 'form' %>

app/views/players/index.html.erb
<div class="page-header">
  <%= link_to new_player_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Player
  <% end %>
  <h1>Listing players</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Image</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Nickname</th>
      <th>Nationality</th>
      <th>Age</th>
      <th>Position</th>
      <th>Team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="players">
    <%= render @players %>
  </tbody>

  <div id="paginator">
    <%= paginate @players, :remote => true%>
  </div>
</table>

app/views/players/index.js.erb
$('#players').html('<%= escape_javascript render(@players) %>');
$('#paginator').html('<%= escape_javascript(paginate(@players, :remote => true).to_s) %>');

app/views/players/new.html.erb
<div class="page-header">
  <%= link_to players_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New player</h1>
</div>

<%= render 'form' %>

app/views/players/report.js.erb
alert('Report generated!');

app/views/players/show.html.erb
<div class="page-header">
  <%= link_to players_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_player_path(@player), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <%= link_to player_report_path(@player), :class => 'btn btn-danger', :remote => true do %>
    <i class="icon-star" %></i>
    Report
  <% end %>
  <h1>Listing players</h1>
</div>

<dl>
  <dt>First name:</dt>
  <dd><%= @player.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @player.last_name %></dd>

  <dt>Nickname:</dt>
  <dd><%= @player.nickname %></dd>

  <dt>Nationality:</dt>
  <dd><%= @player.nationality %></dd>

  <dt>Age:</dt>
  <dd><%= @player.age %></dd>

  <dt>Birth day:</dt>
  <dd><%= @player.birth_day %></dd>

  <dt>Birth country:</dt>
  <dd><%= @player.birth_country %></dd>

  <dt>Birth city:</dt>
  <dd><%= @player.birth_city %></dd>

  <dt>Position:</dt>
  <dd><%= @player.position %></dd>

  <dt>Foot:</dt>
  <dd><%= @player.foot %></dd>

  <dt>Image:</dt>
  <dd><%= @player.image %></dd>

  <dt>Height cm:</dt>
  <dd><%= @player.height_cm %></dd>

  <dt>Weight kg:</dt>
  <dd><%= @player.weight_kg %></dd>

  <dt>Uuid:</dt>
  <dd><%= @player.uuid %></dd>

  <dt>Team uuid:</dt>
  <dd><%= @player.team_uuid %></dd>

  <dt>Team:</dt>
  <dd><%= @player.team_id %></dd>
</dl>