config/routes.rb
JvRailsAudition::Application.routes.draw do
  resources :game_performances


  root to: 'teams#index'

  resources :teams

  resources :players do
    collection do
      get 'page/:page', action: :index
    end
    get 'report', action: :report
  end

  namespace :sponsor do
    resources :companies
  end

  resources :statistics, only: :index

end

app/models/game_performance.rb
class GamePerformance < ActiveRecord::Base
  attr_accessible :aerial_duels_won,
    :assists,
    :goals,
    :pass_success_percentage,
    :player_id,
    :red_cards,
    :shots_per_game,
    :yellow_cards,
    :match_date

  belongs_to :player

  def self.all_games
    GamePerformance.all
  end

  def self.median_goals
    goals = 0.0
    all_games.each do |game|
      goals += game.goals
    end
    median_goals = goals / all_games.count
  end

  def self.sum_goals
    goals = 0.0
    all_games.each do |game|
      goals += game.goals
    end
    goals
  end

  def self.median_assists
    assists = 0.0
    all_games.each do |game|
      assists += game.assists
    end
    median_assists = assists / all_games.count
  end

  def self.sum_assists
    assists = 0.0
    all_games.each do |game|
      assists += game.assists
    end
    assists
  end

  def self.median_yellow_cards
    cards = 0.0
    all_games.each do |game|
      cards += game.yellow_cards
    end
    median_yellow_cards = cards / all_games.count
  end

  def self.sum_yellow_cards
    cards = 0.0
    all_games.each do |game|
      cards += game.yellow_cards
    end
    cards
  end

  def self.median_red_cards
    cards = 0.0
    all_games.each do |game|
      cards += game.red_cards
    end
    median_red_cards = cards / all_games.count
  end

  def self.sum_red_cards
    cards = 0.0
    all_games.each do |game|
      cards += game.red_cards
    end
    cards
  end

  def self.median_shots_per_game
    shots = 0.0
    all_games.each do |game|
      shots += game.shots_per_game
    end
    median_shots_per_game = shots / all_games.count
  end

  def self.sum_shots_per_game
    shots = 0.0
    all_games.each do |game|
      shots += game.shots_per_game
    end
    shots
  end

  def self.median_pass_success_percentage
    pass = 0.0
    all_games.each do |game|
      pass += game.pass_success_percentage
    end
    median_pass_success_percentage = (pass / all_games.count).round(2)
  end

  def self.sum_pass_success_percentage
    pass = 0.0
    all_games.each do |game|
      pass += game.pass_success_percentage
    end
    pass.round(2)
  end

  def self.median_aerial_duels_won
    duels = 0.0
    all_games.each do |game|
      duels += game.aerial_duels_won
    end
    median_aerial_duels_won = duels / all_games.count
  end

  def self.sum_aerial_duels_won
    duels = 0.0
    all_games.each do |game|
      duels += game.aerial_duels_won
    end
    duels
  end

  def self.scrape_data
    page = Nokogiri::HTML(open("public/data/stats.html"))
    array = []
    #grabbing td content and putting it in array
    page.css("td").each do |td|
      array << td.text()
    end
    #slice array to fit each record including show, edit and delete buttons
    new_array = array.each_slice(12).to_a

    CSV.open("table.csv", "w") do |csv|
      new_array.each do |chunk|
        csv << chunk[0...9]
      end
    end

    csv_text = File.read('table.csv')
    csv = CSV.parse(csv_text)
    csv.each do |row|
      GamePerformance.create!(match_date: row[0], goals: row[1], player_id: row[2], assists: row[3], yellow_cards: row[4], red_cards: row[5], shots_per_game: row[6], pass_success_percentage: row[7], aerial_duels_won: row[8] )
    end
  end

end



# == Schema Information
#
# Table name: game_performances
#
#  id                      :integer          not null, primary key
#  goals                   :integer
#  player_id               :integer
#  assists                 :integer
#  yellow_cards            :integer
#  red_cards               :integer
#  shots_per_game          :decimal(, )
#  pass_success_percentage :decimal(, )
#  aerial_duels_won        :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  match_date              :date
#

app/controllers/game_performances_controller.rb
class GamePerformancesController < ApplicationController
  # GET /game_performances
  # GET /game_performances.json
  def index
    @game_performances = GamePerformance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @game_performances }
    end
  end

  # GET /game_performances/1
  # GET /game_performances/1.json
  def show
    @game_performance = GamePerformance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game_performance }
    end
  end

  # GET /game_performances/new
  # GET /game_performances/new.json
  def new
    @game_performance = GamePerformance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game_performance }
    end
  end

  # GET /game_performances/1/edit
  def edit
    @game_performance = GamePerformance.find(params[:id])
  end

  # POST /game_performances
  # POST /game_performances.json
  def create
    @game_performance = GamePerformance.new(params[:game_performance])

    respond_to do |format|
      if @game_performance.save
        format.html { redirect_to @game_performance, notice: 'Game performance was successfully created.' }
        format.json { render json: @game_performance, status: :created, location: @game_performance }
      else
        format.html { render action: "new" }
        format.json { render json: @game_performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /game_performances/1
  # PUT /game_performances/1.json
  def update
    @game_performance = GamePerformance.find(params[:id])

    respond_to do |format|
      if @game_performance.update_attributes(params[:game_performance])
        format.html { redirect_to @game_performance, notice: 'Game performance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game_performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_performances/1
  # DELETE /game_performances/1.json
  def destroy
    @game_performance = GamePerformance.find(params[:id])
    @game_performance.destroy

    respond_to do |format|
      format.html { redirect_to game_performances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/game_performances_helper.rb
module GamePerformancesHelper
end

app/views/game_performances/_form.html.erb
<%= simple_form_for(@game_performance, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :goals %>
    <%= f.input :player_id %>
    <%= f.input :assists %>
    <%= f.input :yellow_cards %>
    <%= f.input :red_cards %>
    <%= f.input :shots_per_game %>
    <%= f.input :pass_success_percentage %>
    <%= f.input :aerial_duels_won %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/game_performances/edit.html.erb
<div class="page-header">
  <%= link_to game_performances_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to @game_performance, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1>Editing game_performance</h1>
</div>

<%= render 'form' %>

app/views/game_performances/index.html.erb
<div class="page-header">
  <%= link_to new_game_performance_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Game performance
  <% end %>
  <h1>Listing game_performances</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Goals</th>
      <th>Player</th>
      <th>Assists</th>
      <th>Yellow cards</th>
      <th>Red cards</th>
      <th>Shots per game</th>
      <th>Pass success percentage</th>
      <th>Aerial duels won</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @game_performances.each do |game_performance| %>
    <tr>
      <td class="match-date"><%= game_performance.match_date %></td>
      <td class="goals"><%= game_performance.goals %></td>
      <td class="player-id"><%= game_performance.player_id %></td>
      <td class="assists"><%= game_performance.assists %></td>
      <td class="yellow-cards"><%= game_performance.yellow_cards %></td>
      <td class="red-cards"><%= game_performance.red_cards %></td>
      <td class="shots-per-game"><%= game_performance.shots_per_game %></td>
      <td class="pass-success-percentage"><%= game_performance.pass_success_percentage %></td>
      <td class="aerial-duels-won"><%= game_performance.aerial_duels_won %></td>
      <td><%= link_to 'Show', game_performance %></td>
      <td><%= link_to 'Edit', edit_game_performance_path(game_performance) %></td>
      <td><%= link_to 'Destroy', game_performance, data: { confirm: 'Are you sure?' }, method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/game_performances/new.html.erb
<div class="page-header">
  <%= link_to game_performances_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New game_performance</h1>
</div>

<%= render 'form' %>

app/views/game_performances/show.html.erb
<div class="page-header">
  <%= link_to game_performances_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_game_performance_path(@game_performance), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Listing game_performances</h1>
</div>

<dl>
  <dt>Goals:</dt>
  <dd><%= @game_performance.goals %></dd>

  <dt>Player:</dt>
  <dd><%= @game_performance.player_id %></dd>

  <dt>Assists:</dt>
  <dd><%= @game_performance.assists %></dd>

  <dt>Yellow cards:</dt>
  <dd><%= @game_performance.yellow_cards %></dd>

  <dt>Red cards:</dt>
  <dd><%= @game_performance.red_cards %></dd>

  <dt>Shots per game:</dt>
  <dd><%= @game_performance.shots_per_game %></dd>

  <dt>Pass success percentage:</dt>
  <dd><%= @game_performance.pass_success_percentage %></dd>

  <dt>Aerial duels won:</dt>
  <dd><%= @game_performance.aerial_duels_won %></dd>

</dl>