config/routes.rb
JvRailsAudition::Application.routes.draw do
  resources :game_performances


  root to: 'teams#index'

  resources :teams

  resources :players do
    collection do
      get 'page/:page', action: :index
    end
    get 'report', action: :report
  end

  namespace :sponsor do
    resources :companies
  end

  resources :statistics, only: :index

end

app/models/sponsor.rb
module Sponsor
  def self.table_name_prefix
    'sponsor_'
  end
end

app/models/sponsor/company.rb
class Sponsor::Company < ActiveRecord::Base
  attr_accessible :net_worth, :name, :type


  def update_net_worth(options = {})
    if options.present?
      self.update_attributes(:net_worth => self.net_worth.to_i + 1000 + options.to_i)
    else
    self.update_attributes(:net_worth => self.net_worth.to_i + 1000)
    end
  end

  def type
    'type'
  end



end

# == Schema Information
#
# Table name: sponsor_companies
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  net_worth  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/sponsor/gold.rb
class Sponsor::Gold < Sponsor::Company

  def name
    raise 'UNKNOWN ERROR'
  end

  def update_net_worth
    super(gold_bonus)
  end

  def gold_bonus
    9000000
  end

end

# == Schema Information
#
# Table name: sponsor_companies
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  net_worth  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/sponsor/companies_controller.rb
class Sponsor::CompaniesController < ApplicationController
  # GET /sponsor/companies
  # GET /sponsor/companies.json
  def index
    @sponsor_companies = Sponsor::Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsor_companies }
    end
  end

  # GET /sponsor/companies/1
  # GET /sponsor/companies/1.json
  def show
    @sponsor_company = Sponsor::Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor_company }
    end
  end

  # GET /sponsor/companies/new
  # GET /sponsor/companies/new.json
  def new
    @sponsor_company = Sponsor::Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor_company }
    end
  end

  # GET /sponsor/companies/1/edit
  def edit
    @sponsor_company = Sponsor::Company.find(params[:id])
  end

  # POST /sponsor/companies
  # POST /sponsor/companies.json
  def create
    @sponsor_company = Sponsor::Company.new(params[:sponsor_company])

    respond_to do |format|
      if @sponsor_company.save
        format.html { redirect_to @sponsor_company, notice: 'Company was successfully created.' }
        format.json { render json: @sponsor_company, status: :created, location: @sponsor_company }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsor/companies/1
  # PUT /sponsor/companies/1.json
  def update
    @sponsor_company = Sponsor::Company.find(params[:id])

    respond_to do |format|
      if @sponsor_company.update_attributes(params[:sponsor_company])
        format.html { redirect_to @sponsor_company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsor/companies/1
  # DELETE /sponsor/companies/1.json
  def destroy
    @sponsor_company = Sponsor::Company.find(params[:id])
    @sponsor_company.destroy

    respond_to do |format|
      format.html { redirect_to sponsor_companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsor/companies_helper.rb
module Sponsor::CompaniesHelper
end

app/views/sponsor/companies/_form.html.erb
<%= simple_form_for(@sponsor_company, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :type %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/sponsor/companies/edit.html.erb
<div class="page-header">
  <%= link_to sponsor_companies_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to @sponsor_company, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1>Editing sponsor_company</h1>
</div>

<%= render 'form' %>

app/views/sponsor/companies/index.html.erb
<div class="page-header">
  <%= link_to new_sponsor_company_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Company
  <% end %>
  <h1>Listing sponsor_companies</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @sponsor_companies.each do |sponsor_company| %>
    <tr>
      <td><%= sponsor_company.name %></td>
      <td><%= sponsor_company.type %></td>
      <td><%= sponsor_company.amount %></td>
      <td><%= link_to 'Show', sponsor_company %></td>
      <td><%= link_to 'Edit', edit_sponsor_company_path(sponsor_company) %></td>
      <td><%= link_to 'Destroy', sponsor_company, data: { confirm: 'Are you sure?' }, method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/sponsor/companies/new.html.erb
<div class="page-header">
  <%= link_to sponsor_companies_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New sponsor_company</h1>
</div>

<%= render 'form' %>

app/views/sponsor/companies/show.html.erb
<div class="page-header">
  <%= link_to sponsor_companies_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_sponsor_company_path(@sponsor_company), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Listing sponsor_companies</h1>
</div>

<dl>
  <dt>Name:</dt>
  <dd><%= @sponsor_company.name %></dd>

  <dt>Type:</dt>
  <dd><%= @sponsor_company.type %></dd>

  <dt>Amount:</dt>
  <dd><%= @sponsor_company.amount %></dd>

</dl>