config/routes.rb
JvRailsAudition::Application.routes.draw do
  resources :game_performances


  root to: 'teams#index'

  resources :teams

  resources :players do
    collection do
      get 'page/:page', action: :index
    end
    get 'report', action: :report
  end

  namespace :sponsor do
    resources :companies
  end

  resources :statistics, only: :index

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Sample</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= li_navbar_link_to 'Teams', teams_path %></li>
            <li><%= li_navbar_link_to 'Players', players_path %></li>
            <li><%= li_navbar_link_to 'Statistics', statistics_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
    <hr>
    <footer>
      <p>&copy; Sample 2014</p>
    </footer>
  </div>
</body>
</html>